/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'emails' : IDL.Vec(IDL.Text),
  'addresses' : IDL.Vec(IDL.Text),
  'phones' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'submitQuote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'emails' : IDL.Vec(IDL.Text),
    'addresses' : IDL.Vec(IDL.Text),
    'phones' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'submitQuote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };